# Generated by Django 6.0.7 on 2026-08-07 01:27

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models

import validibot.validations.models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0038_stepinputbinding_relational_artifact_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validator",
            name="supported_data_formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("json", "JSON"),
                        ("xml", "XML"),
                        ("text", "Plain Text"),
                        ("yaml", "YAML"),
                        ("energyplus_idf", "EnergyPlus IDF"),
                        ("energyplus_epjson", "EnergyPlus epJSON"),
                        ("fmu", "FMU"),
                        ("therm_thmx", "THERM THMX"),
                        ("therm_thmz", "THERM THMZ (Archive)"),
                        ("csv", "CSV (tabular)"),
                        ("pdf", "PDF document package"),
                        ("step_p21", "STEP Part 21"),
                        ("zip", "ZIP archive"),
                        (
                            "portfolio_manager_report",
                            "ENERGY STAR® Portfolio Manager® Report",
                        ),
                        ("unknown", "Unknown"),
                    ],
                    max_length=32,
                ),
                default=validibot.validations.models._default_validator_data_formats,
                help_text=(
                    "Data formats this validator can parse "
                    "(e.g., JSON, EnergyPlus IDF)."
                ),
            ),
        ),
    ]
