# Generated by Django 6.0.7 on 2026-08-11 00:48

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0039_alter_validator_supported_data_formats"),
    ]

    operations = [
        migrations.AddField(
            model_name="callbackreceipt",
            name="delivery_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text=(
                    "Number of callback deliveries that acquired processing ownership."
                ),
            ),
        ),
        migrations.AddField(
            model_name="callbackreceipt",
            name="last_error",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="callbackreceipt",
            name="last_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="callbackreceipt",
            name="processing_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the active callback-processing claim began.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="callbackreceipt",
            name="processing_token",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text=(
                    "Opaque ownership token for the callback processor currently "
                    "performing external work."
                ),
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ValidationRunContinuation",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resume_from_step",
                    models.PositiveIntegerField(
                        help_text=(
                            "Stable order of the completed step; execution resumes "
                            "after it."
                        ),
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending dispatch"),
                            ("DISPATCHING", "Dispatching"),
                            ("DISPATCHED", "Dispatched"),
                            ("EXECUTING", "Executing"),
                            ("COMPLETED", "Completed"),
                            ("NOT_REQUIRED", "No longer required"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "dispatch_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "dispatch_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("dispatch_attempts", models.PositiveIntegerField(default=0)),
                (
                    "transport_task_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "execution_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("execution_attempts", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
                (
                    "callback_receipt",
                    models.OneToOneField(
                        blank=True,
                        help_text="Callback decision that created this continuation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="continuation",
                        to="validations.callbackreceipt",
                    ),
                ),
                (
                    "completed_step_run",
                    models.OneToOneField(
                        help_text=(
                            "Completed step after which workflow execution must resume."
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="continuation",
                        to="validations.validationsteprun",
                    ),
                ),
                (
                    "validation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="continuations",
                        to="validations.validationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
                "indexes": [
                    models.Index(
                        fields=["state", "created"],
                        name="validations_state_e1c8c8_idx",
                    ),
                    models.Index(
                        fields=["state", "dispatch_started_at"],
                        name="validations_state_323e39_idx",
                    ),
                    models.Index(
                        fields=["state", "execution_started_at"],
                        name="validations_state_feb541_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                [
                                    "PENDING",
                                    "DISPATCHING",
                                    "DISPATCHED",
                                    "EXECUTING",
                                    "COMPLETED",
                                    "NOT_REQUIRED",
                                ],
                            ),
                        ),
                        name="ck_validation_continuation_state_known",
                    ),
                ],
            },
        ),
    ]
