# Generated by Django 6.0.7 on 2026-08-12 03:03

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models

import validibot.validations.models


def use_explicit_pdf_file_type(apps, schema_editor):
    """Align existing PDF catalog rows with the dedicated PDF file type."""
    Validator = apps.get_model("validations", "Validator")
    Validator.objects.filter(validation_type="PDF").update(
        supported_file_types=["pdf"],
    )


def restore_binary_pdf_file_type(apps, schema_editor):
    """Restore the pre-PDF-type catalog value when reversing the migration."""
    Validator = apps.get_model("validations", "Validator")
    Validator.objects.filter(validation_type="PDF").update(
        supported_file_types=["binary"],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0040_callbackreceipt_delivery_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validator",
            name="supported_file_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("json", "JSON"),
                        ("xml", "XML"),
                        ("text", "Plain Text"),
                        ("yaml", "YAML"),
                        ("pdf", "PDF"),
                        ("binary", "Binary"),
                        ("UNKNOWN", "Unknown"),
                    ],
                    max_length=32,
                ),
                default=validibot.validations.models._default_validator_file_types,
                help_text=(
                    "Logical file types this validator can process "
                    "(JSON, XML, text, etc.)."
                ),
            ),
        ),
        migrations.RunPython(
            use_explicit_pdf_file_type,
            restore_binary_pdf_file_type,
        ),
    ]
