# Generated by Django 6.0.7 on 2026-08-12 03:03

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models

import validibot.workflows.models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0009_alter_workflow_output_retention"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="allowed_file_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("json", "JSON"),
                        ("xml", "XML"),
                        ("text", "Plain Text"),
                        ("yaml", "YAML"),
                        ("pdf", "PDF"),
                        ("binary", "Binary"),
                        ("UNKNOWN", "Unknown"),
                    ],
                    max_length=32,
                ),
                default=validibot.workflows.models._default_workflow_file_types,
                help_text=(
                    "Logical file types (JSON, XML, text, etc.) this workflow "
                    "can accept."
                ),
            ),
        ),
    ]
