"""Constants for the embedded MCP product surface."""

from enum import StrEnum

from validibot.idp.constants import MCP_OIDC_SCOPE


class MCPErrorCode(StrEnum):
    """Stable errors returned to MCP clients without internal details."""

    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    WORKFLOW_UNAVAILABLE = "WORKFLOW_UNAVAILABLE"
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    INVALID_INPUT = "INVALID_ARGUMENT"
    UNSUPPORTED_FILE = "UNSUPPORTED_FILE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_CONFLICT"
    IDEMPOTENCY_IN_PROGRESS = "IDEMPOTENCY_IN_PROGRESS"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    LAUNCH_DENIED = "PERMISSION_DENIED"
    RATE_LIMITED = "RATE_LIMITED"
    RUN_NOT_COMPLETE = "RUN_NOT_COMPLETE"
    TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE"
    INTERNAL_ERROR = "INTERNAL_ERROR"


MCP_REQUIRED_SCOPE = MCP_OIDC_SCOPE
MCP_DEFAULT_PAGE_SIZE = 20
MCP_MAX_PAGE_SIZE = 50
MCP_MAX_SEARCH_LENGTH = 100
MCP_MAX_IDEMPOTENCY_KEY_LENGTH = 255
MCP_DEFAULT_FILE_MAX_BYTES = 2_500_000
MCP_FILE_DOWNLOAD_TIMEOUT_SECONDS = 15.0
MCP_FILE_DOWNLOAD_TOTAL_TIMEOUT_SECONDS = 30.0
MCP_FILE_DOWNLOAD_MAX_REDIRECTS = 3
MCP_FILE_DOWNLOAD_MAX_ADDRESSES = 4
MCP_MAX_RESPONSE_BYTES = 524_288
MCP_MAX_WORKFLOW_DESCRIPTION_LENGTH = 2_000
MCP_MAX_WORKFLOW_STEPS = 50
MCP_MAX_STEP_TEXT_LENGTH = 1_000
MCP_MAX_FINDING_MESSAGE_LENGTH = 4_000
MCP_MAX_FINDING_PATH_LENGTH = 1_024
MCP_MAX_RESULT_CODE_LENGTH = 255
MCP_MAX_RESULT_NAME_LENGTH = 255
