# Generated by Django 6.0.7 on 2026-08-12 03:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0004_purgeretry_uq_purge_retry_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("json", "JSON"),
                    ("xml", "XML"),
                    ("text", "Plain Text"),
                    ("yaml", "YAML"),
                    ("pdf", "PDF"),
                    ("binary", "Binary"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=64,
            ),
        ),
    ]
